[CPUConfig]
Cores = 1
# Yes, you MIGHT be able to have a multi-cored 6502
CPUScenario = generic6502
# CPUScenario line doesn't do much,
# but I plan to add templates in the future
UnofficialOpcodeSupport = 0
ModifiedInstructionSet = 0

# This currently doesn't do anything
[BuildConfig]
AllowedExtensions = .bin, .obj, .prg, .o65, .rom, .hex, .neo, .abs, .com, .p00, .nes, .obj
UserDefinedAllowedExtensions = none

[AddressSpaceConfig]
ActiveAddressSpaceDevices = 2

[AddressSpaceDeviceOne]
DeviceType = RAM
AddressOffset = 0x0000
AddressSize = 0x2000

[AddressSpaceDeviceTwo]
DeviceType = ROM
AddressOffset = 0x8000
AddressSize = 0x8000

[AddressSpaceDeviceThree]
DeviceType = OpenBus
AddressOffset = 0x2000
AddressSize = 0x6000

# If no device exists on these busses,
# set DeviceType to none
[AddressSpaceDeviceFour]
DeviceType = none

[AddressSpaceDeviceFive]
DeviceType = none

[AddressSpaceDeviceSix]
DeviceType = none

[AddressSpaceDeviceSeven]
DeviceType = none

[AddressSpaceDeviceEight]
DeviceType = none
